import Img1 from "../Assets/bicycles/1.jpg";
import Img2 from "../Assets/bicycles/2.jpg";
import Img3 from "../Assets/bicycles/3.jpg";
import Img4 from "../Assets/bicycles/4.jpg";
import Img5 from "../Assets/bicycles/5.jpg";
import Img6 from "../Assets/bicycles/6.jpg";
import Img7 from "../Assets/bicycles/7.jpg";
import Img8 from "../Assets/bicycles/8.jpg";
import Img9 from "../Assets/bicycles/9.jpg";
import Img10 from "../Assets/bicycles/10.jpg";

const BICYCLES_CONFIG = [
    {
        id:1,
        name:"Mountain Bike Pro",
        description:"Professional mountain bike for extreme trails.",
        rentalPrice:35,
        rating:4.5,
        catergory:"Mountain",
        images:[ Img1, Img5, Img3, Img7],
    },
    {
        id:2,
        name:"Mountain Bike Sport",
        description:"Sport-level mountain bike for intermediate riders.",
        rentalPrice:30,
        rating:4.3,
        catergory:"Mountain",
        images:[Img2, Img8, Img4, Img10],
    },
    {
        id:3,
        name:"Mountain Bike Basic",
        description:"Entry-level mountain bike for beginners.",
        rentalPrice:25,
        rating:4.1,
        catergory:"Mountain",
        images:[Img3, Img6, Img9, Img1],
    },
    {
        id:4,
        name:"Mountain Bike Elite",
        description:"Elite mountain bike with premium components.",
        rentalPrice:40,
        rating:4.7,
        catergory:"Mountain",
        images:[Img4, Img7, Img2, Img5],
    },
    {
        id:5,
        name:"Road Bike Racing",
        description:"High-performance racing road bike.",
        rentalPrice:45,
        rating:4.6,
        catergory:"Road",
        images:[Img8, Img1, Img6, Img3],
    },
    {
        id:6,
        name:"Road Bike Touring",
        description:"Comfortable road bike for long tours.",
        rentalPrice:35,
        rating:4.4,
        catergory:"Road",
        images:[Img9, Img4, Img7, Img2],
    },
    {
        id:7,
        name:"Road Bike Classic",
        description:"Classic road bike for city commuting.",
        rentalPrice:25,
        rating:4.2,
        catergory:"Road",
        images:[Img10, Img5, Img8, Img1],
    },
    {
        id:8,
        name:"Road Bike Carbon",
        description:"Lightweight carbon fiber road bike.",
        rentalPrice:50,
        rating:4.8,
        catergory:"Road",
        images:[Img6, Img3, Img9, Img4],
    },
    {
        id:9,
        name:"Electric City Bike",
        description:"Electric bike perfect for city commuting.",
        rentalPrice:40,
        rating:4.5,
        catergory:"Electric",
        images:[Img7, Img10, Img2, Img5],
    },
    {
        id:10,
        name:"Electric Mountain Bike",
        description:"Electric-powered mountain bike for trails.",
        rentalPrice:60,
        rating:4.8,
        catergory:"Electric",
        images:[Img1, Img8, Img4, Img6],
    },
    {
        id:11,
        name:"Electric Folding Bike",
        description:"Compact electric bike that folds easily.",
        rentalPrice:45,
        rating:4.4,
        catergory:"Electric",
        images:[Img2, Img9, Img7, Img3],
    },
    {
        id:12,
        name:"Electric Cruiser",
        description:"Electric cruiser for comfortable beach rides.",
        rentalPrice:35,
        rating:4.3,
        catergory:"Electric",
        images:[Img5, Img1, Img10, Img8],
    },
    {
        id:13,
        name:"Hybrid Urban",
        description:"Urban hybrid bike for city and light trails.",
        rentalPrice:28,
        rating:4.3,
        catergory:"Hybrid",
        images:[Img3, Img4, Img6, Img9],
    },
    {
        id:14,
        name:"Hybrid Sport",
        description:"Sport hybrid with performance features.",
        rentalPrice:32,
        rating:4.4,
        catergory:"Hybrid",
        images:[Img7, Img2, Img5, Img1],
    },
    {
        id:15,
        name:"Hybrid Comfort",
        description:"Comfort-focused hybrid for casual riding.",
        rentalPrice:26,
        rating:4.2,
        catergory:"Hybrid",
        images:[Img8, Img6, Img3, Img10],
    },
    {
        id:16,
        name:"Hybrid Trekking",
        description:"Trekking hybrid for adventure tours.",
        rentalPrice:30,
        rating:4.5,
        catergory:"Hybrid",
        images:[Img9, Img7, Img4, Img2],
    },
    {
        id:17,
        name:"BMX Freestyle",
        description:"BMX bike designed for freestyle tricks.",
        rentalPrice:22,
        rating:4.1,
        catergory:"BMX",
        images:[Img10, Img1, Img8, Img5],
    },
    {
        id:18,
        name:"BMX Racing",
        description:"Racing BMX for competitive events.",
        rentalPrice:25,
        rating:4.3,
        catergory:"BMX",
        images:[Img4, Img9, Img6, Img7],
    },
    {
        id:19,
        name:"BMX Street",
        description:"Street BMX for urban riding and tricks.",
        rentalPrice:20,
        rating:4.0,
        catergory:"BMX",
        images:[Img2, Img3, Img10, Img1],
    },
    {
        id:20,
        name:"BMX Park",
        description:"Park BMX optimized for skate parks.",
        rentalPrice:23,
        rating:4.2,
        catergory:"BMX",
        images:[Img5, Img8, Img4, Img6],
    },
    {
        id:21,
        name:"City Commuter",
        description:"Practical city bike for daily commuting.",
        rentalPrice:24,
        rating:4.1,
        catergory:"City",
        images:[Img7, Img1, Img9, Img3],
    },
    {
        id:22,
        name:"City Classic",
        description:"Classic city bike with vintage styling.",
        rentalPrice:22,
        rating:4.0,
        catergory:"City",
        images:[Img6, Img10, Img2, Img8],
    },
    {
        id:23,
        name:"City Deluxe",
        description:"Premium city bike with luxury features.",
        rentalPrice:28,
        rating:4.4,
        catergory:"City",
        images:[Img3, Img5, Img7, Img4],
    },
    {
        id:24,
        name:"City Express",
        description:"Fast city bike for quick commutes.",
        rentalPrice:26,
        rating:4.2,
        catergory:"City",
        images:[Img1, Img9, Img6, Img2],
    },
    {
        id:25,
        name:"Kids Mountain Bike",
        description:"Small mountain bike for children.",
        rentalPrice:18,
        rating:4.0,
        catergory:"Kids",
        images:[Img8, Img4, Img10, Img5],
    },
    {
        id:26,
        name:"Kids Road Bike",
        description:"Lightweight road bike for kids.",
        rentalPrice:16,
        rating:3.9,
        catergory:"Kids",
        images:[Img2, Img7, Img3, Img9],
    },
    {
        id:27,
        name:"Kids BMX",
        description:"Small BMX bike for young riders.",
        rentalPrice:15,
        rating:4.1,
        catergory:"Kids",
        images:[Img6, Img1, Img8, Img4],
    },
    {
        id:28,
        name:"Kids Balance Bike",
        description:"Balance bike for learning to ride.",
        rentalPrice:12,
        rating:4.2,
        catergory:"Kids",
        images:[Img10, Img3, Img5, Img7],
    },
    {
        id:29,
        name:"Folding Compact",
        description:"Ultra-compact folding bike for travel.",
        rentalPrice:35,
        rating:4.4,
        catergory:"Folding",
        images:[Img4, Img2, Img9, Img6],
    },
    {
        id:30,
        name:"Folding Electric",
        description:"Electric folding bike with battery assist.",
        rentalPrice:45,
        rating:4.6,
        catergory:"Folding",
        images:[Img8, Img5, Img1, Img10],
    },
]

export{BICYCLES_CONFIG};