
const BICYCLES_CONFIG = [
    {
        id:1,
        name:"Mountain Bike Pro",
        description:"Professional mountain bike for extreme trails.",
        rentalPrice:"₹35/hr",
        rating:4.5,
        catergory:"Mountain",
        images:[],
    },
    {
        id:2,
        name:"Mountain Bike Sport",
        description:"Sport-level mountain bike for intermediate riders.",
        rentalPrice:"₹30/hr",
        rating:4.3,
        catergory:"Mountain",
        images:[],
    },
    {
        id:3,
        name:"Mountain Bike Basic",
        description:"Entry-level mountain bike for beginners.",
        rentalPrice:"₹25/hr",
        rating:4.1,
        catergory:"Mountain",
        images:[],
    },
    {
        id:4,
        name:"Mountain Bike Elite",
        description:"Elite mountain bike with premium components.",
        rentalPrice:"₹40/hr",
        rating:4.7,
        catergory:"Mountain",
        images:[],
    },
    {
        id:5,
        name:"Road Bike Racing",
        description:"High-performance racing road bike.",
        rentalPrice:"₹45/hr",
        rating:4.6,
        catergory:"Road",
        images:[],
    },
    {
        id:6,
        name:"Road Bike Touring",
        description:"Comfortable road bike for long tours.",
        rentalPrice:"₹35/hr",
        rating:4.4,
        catergory:"Road",
        images:[],
    },
    {
        id:7,
        name:"Road Bike Classic",
        description:"Classic road bike for city commuting.",
        rentalPrice:"₹25/hr",
        rating:4.2,
        catergory:"Road",
        images:[],
    },
    {
        id:8,
        name:"Road Bike Carbon",
        description:"Lightweight carbon fiber road bike.",
        rentalPrice:"₹50/hr",
        rating:4.8,
        catergory:"Road",
        images:[],
    },
    {
        id:9,
        name:"Electric City Bike",
        description:"Electric bike perfect for city commuting.",
        rentalPrice:"₹40/hr",
        rating:4.5,
        catergory:"Electric",
        images:[],
    },
    {
        id:10,
        name:"Electric Mountain Bike",
        description:"Electric-powered mountain bike for trails.",
        rentalPrice:"₹60/hr",
        rating:4.8,
        catergory:"Electric",
        images:[],
    },
    {
        id:11,
        name:"Electric Folding Bike",
        description:"Compact electric bike that folds easily.",
        rentalPrice:"₹45/hr",
        rating:4.4,
        catergory:"Electric",
        images:[],
    },
    {
        id:12,
        name:"Electric Cruiser",
        description:"Electric cruiser for comfortable beach rides.",
        rentalPrice:"₹35/hr",
        rating:4.3,
        catergory:"Electric",
        images:[],
    },
    {
        id:13,
        name:"Hybrid Urban",
        description:"Urban hybrid bike for city and light trails.",
        rentalPrice:"₹28/hr",
        rating:4.3,
        catergory:"Hybrid",
        images:[],
    },
    {
        id:14,
        name:"Hybrid Sport",
        description:"Sport hybrid with performance features.",
        rentalPrice:"₹32/hr",
        rating:4.4,
        catergory:"Hybrid",
        images:[],
    },
    {
        id:15,
        name:"Hybrid Comfort",
        description:"Comfort-focused hybrid for casual riding.",
        rentalPrice:"₹26/hr",
        rating:4.2,
        catergory:"Hybrid",
        images:[],
    },
    {
        id:16,
        name:"Hybrid Trekking",
        description:"Trekking hybrid for adventure tours.",
        rentalPrice:"₹30/hr",
        rating:4.5,
        catergory:"Hybrid",
        images:[],
    },
    {
        id:17,
        name:"BMX Freestyle",
        description:"BMX bike designed for freestyle tricks.",
        rentalPrice:"₹22/hr",
        rating:4.1,
        catergory:"BMX",
        images:[],
    },
    {
        id:18,
        name:"BMX Racing",
        description:"Racing BMX for competitive events.",
        rentalPrice:"₹25/hr",
        rating:4.3,
        catergory:"BMX",
        images:[],
    },
    {
        id:19,
        name:"BMX Street",
        description:"Street BMX for urban riding and tricks.",
        rentalPrice:"₹20/hr",
        rating:4.0,
        catergory:"BMX",
        images:[],
    },
    {
        id:20,
        name:"BMX Park",
        description:"Park BMX optimized for skate parks.",
        rentalPrice:"₹23/hr",
        rating:4.2,
        catergory:"BMX",
        images:[],
    },
    {
        id:21,
        name:"City Commuter",
        description:"Practical city bike for daily commuting.",
        rentalPrice:"₹24/hr",
        rating:4.1,
        catergory:"City",
        images:[],
    },
    {
        id:22,
        name:"City Classic",
        description:"Classic city bike with vintage styling.",
        rentalPrice:"₹22/hr",
        rating:4.0,
        catergory:"City",
        images:[],
    },
    {
        id:23,
        name:"City Deluxe",
        description:"Premium city bike with luxury features.",
        rentalPrice:"₹28/hr",
        rating:4.4,
        catergory:"City",
        images:[],
    },
    {
        id:24,
        name:"City Express",
        description:"Fast city bike for quick commutes.",
        rentalPrice:"₹26/hr",
        rating:4.2,
        catergory:"City",
        images:[],
    },
    {
        id:25,
        name:"Kids Mountain Bike",
        description:"Small mountain bike for children.",
        rentalPrice:"₹18/hr",
        rating:4.0,
        catergory:"Kids",
        images:[],
    },
    {
        id:26,
        name:"Kids Road Bike",
        description:"Lightweight road bike for kids.",
        rentalPrice:"₹16/hr",
        rating:3.9,
        catergory:"Kids",
        images:[],
    },
    {
        id:27,
        name:"Kids BMX",
        description:"Small BMX bike for young riders.",
        rentalPrice:"₹15/hr",
        rating:4.1,
        catergory:"Kids",
        images:[],
    },
    {
        id:28,
        name:"Kids Balance Bike",
        description:"Balance bike for learning to ride.",
        rentalPrice:"₹12/hr",
        rating:4.2,
        catergory:"Kids",
        images:[],
    },
    {
        id:29,
        name:"Folding Compact",
        description:"Ultra-compact folding bike for travel.",
        rentalPrice:"₹35/hr",
        rating:4.4,
        catergory:"Folding",
        images:[],
    },
    {
        id:30,
        name:"Folding Electric",
        description:"Electric folding bike with battery assist.",
        rentalPrice:"₹45/hr",
        rating:4.6,
        catergory:"Folding",
        images:[],
    },
]

export{BICYCLES_CONFIG};